Upgrade mongodb to 4.8.1 (min version supporting mongo 6)
balderdashy/sails-mongo pull request #497
Opened 2023-04-17 20:21 UTC by vidueirof

Tested locally with mongo 4, 5 and 6. Also with Atlas (free tier).

2023-04-18 18:32 UTC, vidueirof commented
Mongo node driver 4.x and superior it's not compatible with node 10. More info: https://www.mongodb.com/docs/drivers/node/current/compatibility/#language-compatibility
Node 20 was released, don't you think it's time to deprecate node 10 support?

2023-05-01 07:38 UTC, luislobo commented
I have a PR that updates travis and replaces it with Github actions, using newer mongodb versions. I could add other node versions and MongoDB 6

https://github.com/balderdashy/sails-mongo/pull/495

@mikermcneil What do you think about deprecating non-LTS node versions?

2023-05-02 12:47 UTC, vidueirof commented
At this time node 10 was left behind a long time ago. I think it's time to move forward.
Take a look at current supported versions:
![schedule](https://user-images.githubusercontent.com/5774625/235669879-3403919f-9143-440a-bbb6-03f142d8abe1.svg)

2023-05-02 14:21 UTC, luislobo commented
I think we should get my PR approved first, so that we have a working CI, and then you can update it with the newer mongdb versions.

2023-05-05 21:47 UTC, eashaw requested changes

2023-05-05 21:47 UTC, eashaw commented on lib/private/machines/count-records.js
> +    //mongoCollection.find(mongoWhere).count(function countCb(err, nativeResult) {
Can you remove this comment?

2023-05-05 21:47 UTC, eashaw commented on lib/private/machines/create-each-record.js
> +      });
Is it normally `_id`?

2023-05-05 21:47 UTC, eashaw commented on lib/private/machines/create-record.js
> +      nativeResult.ops = [s3q.newRecord];
Mike: Hmmm, why mutate `nativeResult`?
Should this be `_id`?

2023-12-11 18:21 UTC, closed without merging

2023-12-11 18:21 UTC, DominusKelvin commented
Hey @vidueirof, I'll be closing this PR as this other [PR](https://github.com/balderdashy/sails-mongo/pull/499) has implemented the upgrade and it has been merged. Thank you for working on this 💙

Also you can check here for the upgrade information. 👇🏾

https://blog.sailscasts.com/sails-mongo-v2-1-0